name: Continuous Integration
on:
- push
- pull_request
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install tool dependencies
      run: make install
    - name: Static code analysis
      run: make check
    - name: Validate formatting
      run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
    - name: Build
      run: make build
    - name: Test & generate code coverage
      run: make test
